CREATE TABLE `CUSTOMER` (
     `CUST_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
     `FULL_NAME` varchar(50) NOT NULL,
     `ADDRESS` varchar(50) NOT NULL,
     `EMAIL` varchar(50) NOT NULL,
     PRIMARY KEY (`CUST_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
